---
- name: Configuration deployment with CVP
  hosts: cv_servers
  connection: local
  gather_facts: false
  # collections:
    # - arista.avd
  tasks:
    - name: Upload configlets to support HOSTS configuration
      import_role:
        name: arista.avd.cvp_configlet_upload
      vars:
        configlet_directory: 'intended/configs'
        file_extension: 'cfg'
        configlets_cvp_prefix: 'AVD'
        execute_tasks: true
        cv_collection: v3

    - name: Provision CVP with AVD configuration for Fabric
      import_role:
        name: arista.avd.eos_config_deploy_cvp
      vars:
        container_root: 'ATD_FABRIC'
        configlets_prefix: 'AVD'
        state: present
        execute_tasks: True

    - name: Provision HOSTS containers
      arista.cvp.cv_container_v3:
        topology:
          ATD_FABRIC:
            parentContainerName: Tenant
          ATD_HOSTS:
            parentContainerName: ATD_FABRIC

    - name: Provision HOSTS configuration
      arista.cvp.cv_device_v3:
        devices:
          - fqdn: s1-host1
            parentContainerName: ATD_HOSTS
            configlets:
              - AVD_s1-host1
          - fqdn: s1-host2
            parentContainerName: ATD_HOSTS
            configlets:
              - AVD_s1-host2
      register: cvp_devices_results

    - name: debug
      ansible.builtin.debug:
        msg: 'cvp has {{cvp_devices_results}}'

    - name: "Execute pending tasks on {{ inventory_hostname }}"
      arista.cvp.cv_task_v3:
        tasks: "{{ cvp_devices_results.taskIds }}"
