hostname: s1-host1

static_routes:
- vrf: default
  destination_address_prefix: 0.0.0.0/0
  gateway: 192.168.0.1

service_routing_protocols_model: multi-agent
ip_routing: true

ip_name_servers:
- ip_address: 192.168.2.1
  vrf: default
- ip_address: 8.8.8.8
  vrf: default
spanning_tree:
  mode: mstp
  mst_instances:
  - id: '0'
    priority: 16384

vrfs:
- name: default
  ip_routing: false

management_interfaces:
- name: Management0
  description: oob_management
  shutdown: false
  vrf: default
  ip_address: 192.168.0.16/24
  gateway: 192.168.0.1
  type: oob

management_api_http:
  enable_vrfs:
  - name: default
  enable_https: true

vlans:
- id: 110
  name: Tenant_A_OP_Zone_110
  tenant: Tenant_A

vlan_interfaces:
- name: Vlan110
  description: Tenant_A_OP_Zone_110
  shutdown: false
  mtu: 1500
  ip_address: 10.1.10.11/24

port_channel_interfaces:
- name: Port-Channel2
  description: to s1-leaf-1-2
  type: switched
  shutdown: false
  mode: trunk

ethernet_interfaces:
- name: Ethernet1
  peer: s1-leaf1
  peer_interface: Ethernet4
  type: port-channel-member
  shutdown: false
  channel_group:
    id: 2
    mode: 'on'

- name: Ethernet2
  peer: s1-leaf2
  peer_interface: Ethernet4
  type: port-channel-member
  shutdown: false
  channel_group:
    id: 2
    mode: 'on'

- name: Ethernet3
  peer: s1-leaf3
  peer_interface: Ethernet4
  type: port-channel-member
  shutdown: true
  channel_group:
    id: 2
    mode: 'on'

- name: Ethernet4
  peer: s1-leaf4
  peer_interface: Ethernet4
  type: port-channel-member
  shutdown: true
  channel_group:
    id: 2
    mode: 'on'

ip_igmp_snooping:
  globally_enabled: true
